id: P005365
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC292
  title: བོད་ཀྱི་ཞལ་འབག
  author: ''
  volumes:
    c2879aa6a8fe47ac98dc1b169eaa511c:
      image_group_id: I4PD4199
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
