id: ICAADC212
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:08:00+00:00'
last_modified: '2022-06-08T02:34:10.014907+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC292
  title: བོད་ཀྱི་ཞལ་འབག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A7F7:
      image_group_id: I4PD4199
      title: ''
      total_pages: 202
      order: 1
      base_file: A7F7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
